---

# This is the IP address of your ATEM swithcher
atem_ip: '10.10.1.1'
# If using google slides, set this to the string following the /presentation/d/ section. 
# In the example, below, this would be '209yHgswa8duYISFftQEe3YdGG6hHjZb0JVofPlsD6gA':
# https://docs.google.com/presentation/d/209yHgswa8duYISFftQEe3YdGG6hHjZb0JVofPlsD6gA/edit#slide=id.g25f3c11de7c_0_3
google_slides_id: '134RdRQwa8duYISFftQEe3YMLkiVvNZb0JVoJzinqfmA'
# THis is the path fo the MediaUpload.exe program. If you use setup, you won't have to change this one:
# https://ianmorrish.wordpress.com/atem-command-line-utilites/
media_upload: 'MediaUpload_x64_v9/MediaUpload.exe'
# This is the map of filename:Atem-Slot. The filenames are set on the slides and are assigned during image conversion
media_pool:
   Splash: 1
   Information: 2
   Name_MyName: 3
   Name_YourName: 4
   Donation: 5